print('        ...   ........                                                                              ')
print('     ......    .. .......,..                                                                        ')
print('     . ....    . .,.,:iiiiiii;:,.                                                                   ')
print('     . ....    .,:..::;;:;;;;;:;:,.                            H E L L O                            ')
print('        ...   .,:.,it1:.,,.   ....,.                            B R A D                             ')
print('.      .....  .:.,;1tti.,ii;,.     ,,                                                               ')
print('.             .  ;11ttt1itt1i;,.   ..                                                               ')
print('.             . .iii;i111i;;;;:,. ..                                                                ')
print('.            ,, ,:,..,;1:...,,,,,.  ..                                                              ')
print('.            ., :i;;ii1t;;;;;::,,.  .,.                                                             ')
print('.             ..;111t1t1;i111ii;,...                                                                ')
print('.             ..:iii1i;:,:i1i;::,.,,..                                                              ')
print('.              .:;;i1ii;;;;i;::,,,,,...                                                             ')
print('.........      ..;iii;;;;:,;::::,,.  .                                                              ')
print('....,,,,.      ..,;;iiii;;;;:,,,,,.                                                                 ')
print('...,,,,,.      .. ,:;iii;;;:,,,,,,.                                                                 ')
print('...,,,,,.        ,1:.,,,,,,,,,...,.                                                                 ')
print('..,,,,,,. ..   .iLt;:...........,,::,.                                                              ')
print('..,,,.,,.   .:tCCf1iii:.........,,,i1;:,.                                                           ')
print('..,,..,. .:1LCCf1i1t11i:..   .....:i1tttti1fffffftti:,                                              ')
print('.,,,.,,.:tCCLtiiii1t1tt1i::;;;;;::;;ifLLCCGGGGGCCCCCCLti:.                                          ')
print('.,,...,i1tftftfLLft11fLft111ttffti;itfffttttfftt11iiii1t11i.                                    :tft')
print('......itttfLLttLftt111ttt1111ii;::;i1tt11iiiiiiiii;;::,:;ift1tft1i:.                         :tfLfft')
print('....;tfttttttft11ii1tttt1iii;::;itt11ii1111111111iii;,,;1tLGGGCCCCGCfi:.                     :tt111i')
print('..,;i11iiii1tLLt1ii;i1ii;;;::;i1ttt11iitftt111111iii;,:tt1tLLLLLLLLLCCCt;.           .,,,,::;1111111')
print('..,;;;;i;i11tfftiii;::::,,,,;tft11iiiii;tft1111ii;;::,,;;iiittffLCCCLLffti.    .:i1fLCCCGGCCCfii111i')
print('..,:;;;;;;i11iiiii;;::,....:;;1t1iii;;;;;1111i;;;::,,,,:::;;;iii1tfffft11tfiitfCCGGGGGCCCLLfft1;::::')
print('..::::;;;;;;;;;;iii;;;ii1tttff1ii;;;;;::::;;;::::,,,,.,:i;::::;;;ii11ttfLCGG0GCLLLLLLftttt11i;;;::::')
print('.,:,::::::;;;;;;;;ii1t11tfftfff1;:::,,,,,,,:::::,,,,..,,;1i;:::;;ii11tLffffftttttttt11iiii;;;;:::,,.')
print(',;:,,::::::::::;;ittt1111ttfffff1;,,,,,,,,,.,,:,,,,. ..,:ii11iii111t1iiii111111t1iii;;iii;;;:::::::,')
print(',:;:,:::::::::;ii111111ttfffLLftti:..,,,..,,...,,,.,,...,;;iiii;;;;ii111iiii;;;ii;;;;;;:::::::;;;;;:')
print('.,:::,::;;i1i;;iiiii1fLLtttfftt1i::,......,,,:,...,;;:,,.,::::::it1i:::;;;;;::,::::::::::::;;;:;::::')
print(' .,,,,,,::;i;:;;;;;;iitfLf11tttttftt11111111ii;:,,;;;;;;::,,::iLGGCCLt;,,:,::::::::::::;;;;;::::::::')
print('   .....,::;;:::::::::::iff1ii1tttffffLLLLLLLLLfttftfffttttffLCCLfffttti;;;::;;;;;;;;;;:::::::::::::')
print('      .,..,::::::,,::::::;1tiiiiii;;ii11ttfLCLLffffffLfffffffLfft11ii;;::;;;;;;;;;::::::::::::::::::')
print('       .,,..,:::::::::;;:::;;::::::::;;ii11tttttftttttt111t111iii;:::::::;;:;;::;:::::::::::::::::::')
print('        .,,...,,::::::::::::::::::;;;;iiiiiiiiiiiii;;;;ii;;;;ii;:::::::::::,,:::::;;:;::::::::::::::')
print('         .,,....,,,::::,,,::::;iiii;;;;;;;;;;;;;;;;;;;;::;:::;;:::::::::,,,:,,,::::,,,,:,,,,,:::::::')